package com.nelumbo.migration.exceptions;

import lombok.Getter;

@Getter
public enum ExceptionCodeEnum {
    N01GNR01("No se encontró el ID"),
    N01GNRC01("No se encontró el objeto"),
    C01GNRC01("El objeto ya existe"),
    C01USER01("No se encontró el usuario"),
    C01USER02("El usuario está inactivo"),
    C01USER03("El usuario está bloqueado"),
    C01USER04("El usuario está suspendido"),
    C01USER05("La contraseña ha sido actualizada"),
    C01USER06("Verifique que la contraseña coincida"),
    C01USER07("El usuario no puede ser activado, está en un estado inválido"),
    C01USER08("El usuario ya está activado"),
    C01USER09("El usuario no puede ser activado, no ha completado su perfil"),
    C01USER10("El usuario no puede ser activado, no tiene un período de trabajo asignado"),
    C01USER11("El usuario ya existe"),
    C01USER12("El estado del perfil ya está en uso, no se puede eliminar"),
    C01USER13("El usuario ya está desactivado"),
    C01USER14("El usuario aún no ha completado su perfil"),
    C01USER15("El usuario no puede ser activado, no tiene un gerente de aprobación asignado"),
    C01USER16("No es posible registrarse en la aplicación sin activar al usuario"),
    C01USER17("El perfil del aprobador es inválido o no está activo"),
    C01USER18("El puesto de trabajo del aprobador no corresponde al puesto de trabajo configurado para el perfil"),
    C01USER19("Aún no se ha asignado un puesto de trabajo al perfil"),
    C01USER20("No se puede actualizar el gerente de aprobación, el puesto de trabajo asignado al perfil no tiene un puesto de trabajo establecido como gerente de aprobación"),
    C01USER21("El usuario no puede ser activado, no tiene un puesto de trabajo asignado"),
    C01USER22("El usuario ya está suspendido"),
    C01USER23("No se encontró el gerente de aprobación"),
    C01USER24("El perfil no se puede desactivar, tiene personal asignado"),
    C01USER25("Fechas inválidas, la fecha de inicio no puede ser mayor que la fecha de finalización"),
    C01USER26("Fechas inválidas, la fecha de finalización no puede ser menor que la fecha actual"),
    C01USER27("Fechas inválidas, la fecha de terminación no puede ser menor que la fecha de contratación"),
    C01USER28("Fechas inválidas, la última fecha laborada no puede ser menor que la fecha de contratación"),
    C01USER29("Fechas inválidas, la fecha de terminación del IMSS no puede ser mayor que la fecha de contratación"),
    C01USER30("Fechas inválidas, ya existe una solicitud en el bloque de fechas solicitado"),
    C01USER31("Fechas inválidas, la fecha de terminación no puede ser menor que la fecha actual"),
    C01USER32("Ya existe una desactivación programada para este perfil"),
    C01USER33("El correo electrónico del usuario ya existe"),
    C01USER34("El usuario no puede ser activado, no tiene un gerente de aprobación activo asignado"),
    C01USER35("No se puede asignar el puesto de trabajo, ha completado el personal autorizado"),
    C01ORGE01("Debe agregar al menos un campo"),
    C01ORGE02("La entidad de la organización no se puede eliminar, tiene detalles asignados"),
    C01ORGE03("El id de la entidad está duplicado en la lista"),
    C01ORGE04("La entidad principal de la organización no es del tipo de entidad secundaria de la organización"),
    C01ORGE05("La entidad de la organización no se puede asignar, tiene detalles asignados"),
    C01ORGE06("El tipo de entidad de la organización está completo"),
    C01ORGE07("Hay más de un padre para el tipo de entidad de la organización"),
    C01ORGE08("La entidad de la organización no se puede eliminar, tiene campos asignados"),
    C01ORGE09("No se puede eliminar la entidad porque está vinculada a otras entidades"),
    C01ORGE10("No se encontró la entidad de la organización"),
    C01ORGE11("La entidad de la organización ya existe"),
    C01OFLD01("No es válido actualizar el tipo de campo, verifique"),
    C01OFLD02("El catalogueId no puede estar vacío para el tipo de catálogo"),
    C01OFLD03("El campo min_chars no es válido"),
    C01OFLD04("El campo max_chars no es válido"),
    C01OFLD05("El campo min_value no es válido"),
    C01OFLD06("El campo max_value no es válido"),
    C01OFLD07("El campo required no es válido"),
    C01OFLD08("El campo unique no es válido"),
    C01OFLD09("Los campos min_chars y max_chars son obligatorios para el tipo de texto"),
    C01OFLD10("Los campos min_value y max_value son obligatorios para el tipo numérico"),
    C01OFLD11("Los campos min_currency y max_currency son obligatorios para el tipo moneda"),
    C01OFLD12("El campo no es válido"),
    C01OFLD13("El valor excede la posición máxima posible"),
    C01OFLD14("No se encontró el campo"),
    C01OFLD15("El campo ya existe"),
    C01OFLD16("El campo max_size no es válido"),
    C01OFLD17("El campo file_type no es válido"),
    C01OFLD18("Los campos max_size y file_type son obligatorios para el tipo de archivo"),
    C01OFLD19("El campo max_range no es válido"),
    C01OFLD20("El campo max_date no es válido"),
    C01OFLD21("El campo min_time no es válido"),
    C01OFLD22("El campo max_time no es válido"),
    C01OFLD23("Los campos max_range y max_date son obligatorios para el tipo de archivo"),
    C01OFLD24("Los campos min_time y max_time son obligatorios para el tipo de archivo"),
    C01OFLD25("El tamaño del archivo excede el máximo permitido"),
    C01OFLD26("El tipo de archivo no es válido"),
    C01OFLD27("El rango máximo no es válido"),
    C01OFLD28("La fecha máxima no es válida"),
    C01OFLD29("La hora mínima no es válida"),
    C01OFLD30("La hora máxima no es válida"),
    C01OFLD31("El campo min_currency no es válido"),
    C01OFLD32("El campo max_currency no es válido"),
    C01OFLD33("El monto mínimo en moneda no es válido"),
    C01OFLD34("El monto máximo en moneda no es válido"),
    C01OFLD35("Aún no se ha definido una estructura geográfica"),
    C01OFLD36("Se requiere la profundidad para el tipo de campo geográfico"),
    C01OFLD37("La estructura geográfica no es válida"),
    C01OFLD38("El campo ya está en uso, no se puede editar"),
    C01OFLD39("La estructura geográfica del campo no se puede editar"),
    C01OFLD40("El campo subdirectories no es válido"),
    C01OFLD41("Los campos subdirectories y file_type son obligatorios para el tipo de directorio"),
    C01OFLD42("El campo no es una fecha válida"),
    C01OFLD43("El campo no es un binario válido"),
    C01OFLD44("La fecha es anterior a la fecha actual"),
    C01OFLD45("La fecha es posterior a la fecha actual"),
    C01OFLD46("El campo solo acepta carácteres en mayúsculas"),
    C01OFLD47("El campo future_date no es válido"),
    C01OFLD48("El campo past_date no es válido"),
    C01OFLD49("El campo to_upper_casee no es válido"),
    C01ORGD01("El detalle de la entidad de la organización no se puede actualizar, ya tiene registros asociados"),
    C01ORGD02("El campo es obligatorio"),
    C01ORGD03("El campo no es único"),
    C01ORGD04("El campo tiene menos caracteres de los mínimos requeridos"),
    C01ORGD05("El campo tiene más caracteres de los máximos permitidos"),
    C01ORGD06("El campo tiene un valor menor al mínimo permitido"),
    C01ORGD07("El campo tiene un valor mayor al máximo permitido"),
    C01ORGD08("El campo no es válido"),
    C01ORGD09("El detalle de la entidad de la organización no se puede eliminar, ya tiene registros asociados"),
    C01ORGD10("El detalle de la entidad de la organización no se puede eliminar, está relacionado como padre"),
    C01ORGD11("No se encontró el detalle de la entidad de la organización"),
    C01ORGD12("El detalle de la entidad de la organización ya existe"),
    C01ORGD13("El detalle de la estructura de la entidad de la organización no está relacionado con este padre"),
    C01ORGD14("La estructura del detalle de la entidad de la organización no está completa"),
    C01ORET01("La configuración no se ha completado"),
    C01ORGR01("No se encontró la relación de la entidad de la organización"),
    C01ORGR02("La relación de la entidad de la organización ya existe"),
    C01ORGR03("La lista de relaciones de la entidad de la organización no puede estar vacía"),
    C01ORGR04("No se pudo crear la relación, ya existe un modelo de centro de costo relacionado"),
    C01ORGR05("No se pudo crear la relación, ya existe un modelo de pestaña de compensación relacionado"),
    C01ORGR06("No se pudo crear la relación, ya existe un modelo de tienda relacionado"),
    C01ORGR07("No se pudo crear la relación, ya existe un modelo de categoría de compensación relacionado"),
    C01ORGR08("No se pudo crear la relación, ya existe un modelo de puesto de trabajo relacionado"),
    C01ORGR09("No se pudo crear la relación, ya existe un modelo de categoría de puesto de trabajo relacionado"),
    C01ORGR10("No se encontró un nombre de modelo que coincida"),
    C01MDLN01("El nombre del modelo ya se está utilizando, no se puede eliminar"),
    C01MDLN02("No se encontró el nombre del modelo"),
    C01MDLN03("El nombre del modelo ya existe"),
    C01MDFD01("El campo del modelo ya está en uso, no se puede editar"),
    C01MDFD02("El campo del modelo ya está en uso, no se puede eliminar"),
    C01MDFD03("No es válido actualizar el tipo de campo del modelo, verifique"),
    C01MDFD04("El catalogueId no puede estar vacío"),
    C01MDFD05("El valor excede la posición máxima posible"),
    C01MDFD06("No se encontró el campo del modelo"),
    C01MDFD07("El campo del modelo ya existe"),
    C01MDFD08("La acción (eliminar) no se puede realizar porque el campo del modelo está bloqueado"),
    C01MDFD09("La acción (actualizar) no se puede realizar porque el campo del modelo está bloqueado"),
    C01MDFD10("El valor excede la posición máxima posible"),
    C01PSFD01("No se encontró el campo de la sección del perfil"),
    C01PSFD02("El campo de la sección del perfil ya está en uso, no se puede eliminar"),
    C01PSFD03("La acción (eliminar) no se puede realizar porque el campo de la sección del perfil está bloqueado"),
    C01PSFD04("El campo de la sección del perfil ya existe"),
    C01PSFD05("El catalogueId no puede estar vacío"),
    C01PSFD06("El valor excede la posición máxima posible"),
    C01CSTC01("La lista de campos del modelo no puede estar vacía"),
    C01CSTC02("El centro de costo ya está en uso, no se puede eliminar"),
    C01CSTC03("Debe agregar al menos un detalle del centro de costo"),
    C01CSTC04("El campo es obligatorio"),
    C01CSTC05("El campo no es único"),
    C01CSTC06("El campo tiene menos caracteres de los mínimos requeridos"),
    C01CSTC07("El campo tiene más caracteres de los máximos permitidos"),
    C01CSTC08("El campo tiene un valor menor al mínimo permitido"),
    C01CSTC09("El campo tiene un valor mayor al máximo permitido"),
    C01CSTC10("El campo no es válido"),
    C01CSTC11("No hay campos de modelo relacionados"),
    C01CSTC12("No se puede desactivar porque está en uso"),
    C01CSTC13("No se encontró el centro de costo"),
    C01CSTC14("El centro de costo ya existe"),
    C01CSTC15("El tamaño del archivo excede el máximo permitido"),
    C01CSTC16("El tipo de archivo no es válido"),
    C01CSTC17("El detalle del centro de costo ya existe"),
    C01CSTC18("No se encontró el detalle del centro de costo"),
    C01CSTC19("El rango máximo no es válido"),
    C01CSTC20("La fecha máxima no es válida"),
    C01CSTC21("La hora mínima no es válida"),
    C01CSTC22("La hora máxima no es válida"),
    C01CSTC23("El monto mínimo en moneda no es válido"),
    C01CSTC24("El monto máximo en moneda no es válido"),
    C01CSTC25("El código ya existe"),
    C01CSTC26("La denominación ya existe"),
    C01CSTC27("La estructura geográfica no es válida"),
    C01CSTC28("La fecha es anterior a la fecha actual"),
    C01CSTC29("La fecha es posterior a la fecha actual"),
    C01CSTC30("El campo solo acepta mayúsculas"),
    C01CCAT01("No se encontró la categoría de compensación"),
    C01CCAT02("La categoría de compensación ya existe"),
    C01CCAT03("La categoría de compensación ya está en uso, no se puede eliminar"),
    C01CCAT04("El campo es obligatorio"),
    C01CCAT05("El campo no es único"),
    C01CCAT06("El campo tiene menos caracteres de los mínimos requeridos"),
    C01CCAT07("El campo tiene más caracteres de los máximos permitidos"),
    C01CCAT08("El campo tiene un valor menor al mínimo permitido"),
    C01CCAT09("El campo tiene un valor mayor al máximo permitido"),
    C01CCAT10("El campo es inválido"),
    C01CCAT11("El campo excede el tamaño máximo permitido"),
    C01CCAT12("El tipo de campo no es válido"),
    C01CCAT13("No se puede desactivar porque está en uso"),
    C01CCAT14("El campo está fuera del rango máximo permitido"),
    C01CCAT15("El campo excede la fecha máxima permitida"),
    C01CCAT16("El campo está por debajo de la hora mínima permitida"),
    C01CCAT17("El campo excede la hora máxima permitida"),
    C01CCAT18("El campo está por debajo del monto mínimo de moneda permitido"),
    C01CCAT19("El campo excede el monto máximo de moneda permitido"),
    C01CCAT20("El código ya existe"),
    C01CCAT21("La denominación ya existe"),
    C01CCAT22("La estructura geográfica no cumple con la estructura predefinida"),
    C01CCAT23("El campo está antes de la fecha actual"),
    C01CCAT24("El campo está después de la fecha actual"),
    C01CCAT25("El campo solo acepta caracteres en mayúsculas"),
    C01CTAB01("No se encontró la pestaña de compensación"),
    C01CTAB02("La pestaña de compensación ya existe"),
    C01CTAB03("La pestaña de compensación ya está en uso, no se puede eliminar"),
    C01CTAB04("El campo es obligatorio"),
    C01CTAB05("El campo no es único"),
    C01CTAB06("El campo tiene menos caracteres que el mínimo requerido"),
    C01CTAB07("El campo tiene más caracteres que el máximo permitido"),
    C01CTAB08("El campo tiene un número menor que el mínimo permitido"),
    C01CTAB09("El campo tiene un número mayor que el máximo permitido"),
    C01CTAB10("El campo es inválido"),
    C01CTAB11("Debe agregar al menos un detalle de pestaña de compensación"),
    C01CTAB12("No se puede desactivar porque está en uso"),
    C01CTAB13("El campo excede el tamaño máximo permitido"),
    C01CTAB14("El tipo de campo no es válido"),
    C01CTAB15("El campo está fuera del rango máximo permitido"),
    C01CTAB16("El campo excede la fecha máxima permitida"),
    C01CTAB17("El campo está por debajo de la hora mínima permitida"),
    C01CTAB18("El campo excede la hora máxima permitida"),
    C01CTAB19("El campo está por debajo del monto mínimo de moneda permitido"),
    C01CTAB20("El campo excede el monto máximo de moneda permitido"),
    C01CTAB21("El código ya existe"),
    C01CTAB22("La denominación ya existe"),
    C01CTAB23("La estructura geográfica no cumple con la estructura predefinida"),
    C01CTAB24("El campo está antes de la fecha actual"),
    C01CTAB25("El campo está después de la fecha actual"),
    C01CTAB26("El campo solo acepta caracteres en mayúsculas"),
    C01STRE01("No se encontró la tienda"),
    C01STRE02("La tienda ya existe"),
    C01STRE03("Debe agregar al menos un detalle de la tienda"),
    C01STRE04("El campo es obligatorio"),
    C01STRE05("El campo no es único"),
    C01STRE06("El campo tiene menos caracteres que el mínimo requerido"),
    C01STRE07("El campo tiene más caracteres que el máximo permitido"),
    C01STRE08("El campo tiene un número menor que el mínimo permitido"),
    C01STRE09("El campo tiene un número mayor que el máximo permitido"),
    C01STRE10("El campo es inválido"),
    C01STRE11("El campo excede el tamaño máximo permitido"),
    C01STRE12("El tipo de campo no es válido"),
    C01STRE13("No se puede desactivar porque está en uso"),
    C01STRE14("La tienda ya está en uso, no se puede eliminar"),
    C01STRE15("El detalle de la tienda ya existe"),
    C01STRE16("No se encontró el detalle de la tienda"),
    C01STRE17("El campo está fuera del rango máximo permitido"),
    C01STRE18("El campo excede la fecha máxima permitida"),
    C01STRE19("El campo está por debajo de la hora mínima permitida"),
    C01STRE20("El campo excede la hora máxima permitida"),
    C01STRE21("No se encontró el periodo de trabajo de la tienda"),
    C01STRE22("El periodo de trabajo de la tienda ya existe"),
    C01STRE23("La estructura geográfica ya está definida"),
    C01STRE24("El campo está por debajo del monto mínimo de moneda permitido"),
    C01STRE25("El campo excede el monto máximo de moneda permitido"),
    C01STRE26("El código ya existe"),
    C01STRE27("La denominación ya existe"),
    C01STRE28("La estructura geográfica no cumple con la estructura predefinida"),
    C01STRE29("El campo está antes de la fecha actual"),
    C01STRE30("El campo está después de la fecha actual"),
    C01STRE31("El campo solo acepta caracteres en mayúsculas"),
    C01WPCA01("No se encontró la categoría de puesto de trabajo"),
    C01WPCA02("La categoría de puesto de trabajo ya existe"),
    C01WPCA03("La categoría de puesto de trabajo ya está en uso, no se puede eliminar"),
    C01WPCA04("Debe agregar al menos un detalle de categoría de puesto de trabajo"),
    C01WPCA05("El campo es obligatorio"),
    C01WPCA06("El campo no es único"),
    C01WPCA07("El campo tiene menos caracteres que el mínimo requerido"),
    C01WPCA08("El campo tiene más caracteres que el máximo permitido"),
    C01WPCA09("El campo tiene un número menor que el mínimo permitido"),
    C01WPCA10("El campo tiene un número mayor que el máximo permitido"),
    C01WPCA11("El campo es inválido"),
    C01WPCA12("El campo excede el tamaño máximo permitido"),
    C01WPCA13("El tipo de campo no es válido"),
    C01WPCA14("No se puede desactivar porque está en uso"),
    C01WPCA15("El campo está fuera del rango máximo permitido"),
    C01WPCA16("El campo excede la fecha máxima permitida"),
    C01WPCA17("El campo está por debajo de la hora mínima permitida"),
    C01WPCA18("El campo excede la hora máxima permitida"),
    C01WPCA19("El campo está por debajo del monto mínimo de moneda permitido"),
    C01WPCA20("El campo excede el monto máximo de moneda permitido"),
    C01WPCA21("El código ya existe"),
    C01WPCA22("La denominación ya existe"),
    C01WPCA23("La estructura geográfica no cumple con la estructura predefinida"),
    C01WPCA24("El campo está antes de la fecha actual"),
    C01WPCA25("El campo está después de la fecha actual"),
    C01WPCA26("El campo solo acepta caracteres en mayúsculas"),
    C01WPOS01("No se encontró el puesto de trabajo"),
    C01WPOS02("El puesto de trabajo ya existe"),
    C01WPOS03("El puesto de trabajo ya está en uso, no se puede eliminar"),
    C01WPOS04("Debe agregar al menos un detalle de puesto de trabajo"),
    C01WPOS05("El campo es obligatorio"),
    C01WPOS06("El campo no es único"),
    C01WPOS07("El campo tiene menos caracteres que el mínimo requerido"),
    C01WPOS08("El campo tiene más caracteres que el máximo permitido"),
    C01WPOS09("El campo tiene un número menor que el mínimo permitido"),
    C01WPOS10("El campo tiene un número mayor que el máximo permitido"),
    C01WPOS11("El campo es inválido"),
    C01WPOS12("El campo excede el tamaño máximo permitido"),
    C01WPOS13("El tipo de campo no es válido"),
    C01WPOS14("No se puede desactivar porque está en uso"),
    C01WPOS15("El campo está fuera del rango máximo permitido"),
    C01WPOS16("El campo excede la fecha máxima permitida"),
    C01WPOS17("El campo está por debajo de la hora mínima permitida"),
    C01WPOS18("El campo excede la hora máxima permitida"),
    C01WPOS19("El detalle del puesto de trabajo ya existe"),
    C01WPOS20("No se encontró el detalle del puesto de trabajo"),
    C01WPOS21("Se requiere la estructura organizativa"),
    C01WPOS22("El puesto de trabajo no se puede activar porque está incompleto"),
    C01WPOS23("La estructura geográfica ya está definida"),
    C01WPOS24("El campo está por debajo del monto mínimo de moneda permitido"),
    C01WPOS25("El campo excede el monto máximo de moneda permitido"),
    C01WPOS26("El código ya existe"),
    C01WPOS27("La denominación ya existe"),
    C01WPOS28("La estructura geográfica no cumple con la estructura predefinida"),
    C01WPOS29("El personal autorizado no se puede actualizar, es menor al que está en uso"),
    C01WPOS30("El campo está antes de la fecha actual"),
    C01WPOS31("El campo está después de la fecha actual"),
    C01WPOS32("El campo solo acepta caracteres en mayúsculas"),
    C01PRSE01("Las secciones de perfil ya existen"),
    C01PRSE02("No se encontraron las secciones de perfil"),
    C01PRSE03("El valor excede la posición máxima posible"),
    C01PRSE04("El peso total de las secciones de perfil supera el 100%"),
    C01PRSE05("El peso total de las secciones de perfil debe ser del 100%"),
    C01PRSE06("No se puede desactivar porque ya tiene múltiples registros"),
    C01PRSV01("No se encontró el valor de la sección de perfil"),
    C01PRSV02("El valor de la sección de perfil ya existe"),
    C01PRSV03("El campo no es único"),
    C01PRSV04("El campo es obligatorio"),
    C01PRSV05("El campo tiene menos caracteres que el mínimo requerido"),
    C01PRSV06("El campo tiene más caracteres que el máximo permitido"),
    C01PRSV07("El campo tiene un número menor que el mínimo permitido"),
    C01PRSV08("El campo tiene un número mayor que el máximo permitido"),
    C01PRSV09("El campo excede el tamaño máximo permitido"),
    C01PRSV10("El tipo de campo no es válido"),
    C01PRSV11("El campo está fuera del rango máximo permitido"),
    C01PRSV12("El campo excede la fecha máxima permitida"),
    C01PRSV13("El campo está por debajo de la hora mínima permitida"),
    C01PRSV14("El campo excede la hora máxima permitida"),
    C01PRSV15("El campo está por debajo del monto mínimo de moneda permitido"),
    C01PRSV16("El campo excede el monto máximo de moneda permitido"),
    C01PRSV17("El campo es inválido"),
    C01PRSV18("La estructura geográfica no cumple con la estructura predefinida"),
    C01PRSV19("El campo está antes de la fecha actual"),
    C01PRSV20("El campo está después de la fecha actual"),
    C01PRSV21("El campo solo acepta caracteres en mayúsculas");
    private final String code;
    private final String message;

    ExceptionCodeEnum(String message) {
        this.code = this.name();
        this.message = message;
    }
    public static String getMessageFromCode(String code) {
        for (ExceptionCodeEnum exc : values()) {
            if (exc.getCode().equalsIgnoreCase(code)) {
                return exc.getMessage();
            }
        }
        return "";
    }
}
