server:
  port: 8544
hrcore:
  organization-api: ${HRCORE_ORGANIZATION_API:https://hqedejv4h2.execute-api.us-east-1.amazonaws.com/dev/api1}
logging:
  file:
    name: /var/www/html/migration/migrationdev/migrationdev.log