spring:
  application:
    name: migration
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 90000