server:
  port: 8081

spring:
  application:
    name: migration
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local

email: ${EMAIL}
password: ${PASSWORD}

logging:
  file:
    name: ./migration.log