server:
  port: 8545
hrcore:
  organization-api: ${HRCORE_ORGANIZATION_API:https://hqedejv4h2.execute-api.us-east-1.amazonaws.com/qa/api1}
logging:
  file:
    name: /var/www/html/migration/migrationqa/migrationqa.log