server:
  port: 8546

spring:
  application:
    name: migration
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev

logging:
  file:
    name: /var/www/html/migration/migration.log